export const INTRO_VIDEO_FALLBACK_URL =
  process.env.NEXT_PUBLIC_INTRO_VIDEO_URL ??
  "https://roeobspqokpkhwbduyid.supabase.co/storage/v1/object/sign/videos/ExploreYou%20Intro.mp4?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xZWQzMmUyYS1mYTY4LTQ3MjgtYWYxOC1kNDE4NTRlMDI0ZTciLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWRlb3MvRXhwbG9yZVlvdSBJbnRyby5tcDQiLCJpYXQiOjE3NTk0MDI5NjgsImV4cCI6MTc2MDAwNzc2OH0.nfAVsftIkOOvjHdcXf9P3bZET25v8G1pGOe_GEz7NN0"

export const STUDY_STREAMS_VIDEO_FALLBACK_URL =
  process.env.NEXT_PUBLIC_STUDY_STREAMS_VIDEO_URL ??
  "https://roeobspqokpkhwbduyid.supabase.co/storage/v1/object/sign/videos/generated_video_20250917_0737.mp4?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8xZWQzMmUyYS1mYTY4LTQ3MjgtYWYxOC1kNDE4NTRlMDI0ZTciLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWRlb3MvZ2VuZXJhdGVkX3ZpZGVvXzIwMjUwOTE3XzA3MzcubXA0IiwiaWF0IjoxNzU5NDAzMzA2LCJleHAiOjE3NjAwMDgxMDZ9.zaCrsa8y7NIMrFW89qLnaJaP37IFJ2HmKh0u2FtGZ9g"
